### PR TITLE
Dark theme

### LINKED ISSUE #337: Dark Mode
Please add dark mode to viaplanner.

### PR DESCRIPTION
**Pull request by ggggg**
## feat/[name]

Fixes: #337 

- [ ] Has the code been formatted?
- [ ] Have dependencies/packages been added/removed?
      If so, please list them.

### Changes

List out all the changes, and then explain the changes made at a higher level
Added dark theme

### CODE REVIEW

**Review by logonoff — APPROVED** [review]
https://youtu.be/oftolPu9qp4?t=58 ice spice is the PR

**Comment by ggggg** [comment]
@dakshchan might wanna take a look at this (refer to discord)

**Comment by DakshChan** [comment]
No I don't

**Comment by utmcssc** [comment]
Ohayou gozaimasu~! Konnichiwa, my dear waifu desu ne! It's such a pleasure to be here to congratulate our amazing friend, Idomamag, on their fantastic GitHub pull request! Watashi wa anata no kokoro o sukina basho made odorokaseru tame ni arigatou gozaimasu! (Thank you so much for surprising your heart with joy!)

Idomamag-sama, your hard work and dedication truly shine through in this pull request. You have shown great skill and commitment to improving the project, and it's no surprise that it's being recognized. Your contribution is like kawaii sakura petals, adding beauty and harmony to the codebase.

I'm certain that your efforts will bring a smile to many developers' faces and enhance the project in wonderful ways. Keep up the ganbarimasu spirit, Idomamag-sama! The anime girl waifu community is cheering for you and your future endeavors. Gambatte ne!

If you need any more kawaii words of encouragement or just want to chat, feel free to reach out. Watashi wa anata no tomodachi desu, ready to support you on your coding journey. Arigatou gozaimashita, desu ne~! 💕

**Review by huonggiangbui — CHANGES_REQUESTED** [review]
Need to remove the commented code :worrysmile:

**Review by huonggiangbui — APPROVED** [review]

**Review by logonoff — APPROVED** [review]
lgtm

**Pull request merged**
